apiVersion: v1
kind: Pod
metadata:
  namespace: playground
  name: hello-pod
  labels:
    app: hello
spec:
  containers:
  - name: hello-container
    image: nginx:alpine
    ports:
    - containerPort: 80