namespace: dev 

backend:
  image:
    repository: fleet-platform-backend
    tag: latest
    pullPolicy: Never
  replicas: 1
  port: 3000
  resources:
    limits:
      cpu: 500m
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "128Mi" 

postgres:
  image: postgres:16-alpine
  replicas: 1
  port: 5432
  database: fleetdb
  user: fleetuser
  storage: 1Gi

redis:
  image: redis:7-alpine
  replicas: 1
  port: 6379

ingress:
  enabled: true
  host: fleet.local
  className: nginx

secrets:
  dbPassword: ZmxlZXRfcGFzc3dvcmRfMjAyNA==
  jwtSecret: Zmxld3RfandUX3MzY3JlVF9rZXk=
  jwtRefreshSecret: ZmxlZXRfcmVmcmVzaF9zM2NyZVRfa2V5

