apiVersion: v1
kind: ConfigMap
metadata:
  name: fleet-config
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "fleetdb"
  DB_USER: "fleetuser"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  NODE_ENV: "production"
  PORT: "3000"
  CORS_ORIGIN: "http://localhost:5173"