apiVersion: v1
kind: Secret
metadata:
  name: fleet-secret
type: Opaque
data:
  DB_PASSWORD: ZmxlZXRfcGFzc3dvcmRfMjAyNA==
  JWT_SECRET: Zmxld3RfandUX3MzY3JlVF9rZXk=
  JWT_REFRESH_SECRET: ZmxlZXRfcmVmcmVzaF9zM2NyZVRfa2V5