apiVersion: v1
kind: Secret
metadata:
  name: fleet-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secrets.dbPassword }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret }}
  JWT_REFRESH_SECRET: {{ .Values.secrets.jwtRefreshSecret }}